"""fix_timestamp_defaults

Revision ID: 7a1335ae5d93
Revises: 4d5cc6610e00
Create Date: 2025-11-30 02:24:44.810105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1335ae5d93'
down_revision: Union[str, Sequence[str], None] = '4d5cc6610e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
