"""fix_relationship_issue

Revision ID: 9f17d3fb383a
Revises: 7a1335ae5d93
Create Date: 2025-12-01 01:29:47.095376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f17d3fb383a'
down_revision: Union[str, Sequence[str], None] = '7a1335ae5d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_configs_id'), table_name='alert_configs')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_constraint(op.f('alerts_job_id_fkey'), 'alerts', type_='foreignkey')
    op.drop_constraint(op.f('alerts_alert_config_id_fkey'), 'alerts', type_='foreignkey')
    op.drop_constraint(op.f('alerts_pipeline_id_fkey'), 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'alert_configs', ['alert_config_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'alerts', 'pipelines', ['pipeline_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'alerts', 'jobs', ['job_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('connections_name_key'), 'connections', type_='unique')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.create_index(op.f('ix_connections_name'), 'connections', ['name'], unique=True)
    op.drop_index(op.f('ix_job_logs_id'), table_name='job_logs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.create_index(op.f('ix_jobs_pipeline_id'), 'jobs', ['pipeline_id'], unique=False)
    op.drop_index(op.f('ix_metadata_cache_id'), table_name='metadata_cache')
    op.create_index(op.f('ix_metadata_cache_connection_id'), 'metadata_cache', ['connection_id'], unique=False)
    op.drop_index(op.f('ix_pipeline_states_id'), table_name='pipeline_states')
    op.drop_index(op.f('ix_pipeline_versions_id'), table_name='pipeline_versions')
    op.drop_index(op.f('ix_pipelines_id'), table_name='pipelines')
    op.drop_constraint(op.f('pipelines_name_key'), 'pipelines', type_='unique')
    op.create_index(op.f('ix_pipelines_destination_connection_id'), 'pipelines', ['destination_connection_id'], unique=False)
    op.create_index(op.f('ix_pipelines_name'), 'pipelines', ['name'], unique=True)
    op.create_index(op.f('ix_pipelines_source_connection_id'), 'pipelines', ['source_connection_id'], unique=False)
    op.drop_index(op.f('ix_system_config_id'), table_name='system_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_system_config_id'), 'system_config', ['id'], unique=False)
    op.drop_index(op.f('ix_pipelines_source_connection_id'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_name'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_destination_connection_id'), table_name='pipelines')
    op.create_unique_constraint(op.f('pipelines_name_key'), 'pipelines', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_pipelines_id'), 'pipelines', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_versions_id'), 'pipeline_versions', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_states_id'), 'pipeline_states', ['id'], unique=False)
    op.drop_index(op.f('ix_metadata_cache_connection_id'), table_name='metadata_cache')
    op.create_index(op.f('ix_metadata_cache_id'), 'metadata_cache', ['id'], unique=False)
    op.drop_index(op.f('ix_jobs_pipeline_id'), table_name='jobs')
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_job_logs_id'), 'job_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_connections_name'), table_name='connections')
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_unique_constraint(op.f('connections_name_key'), 'connections', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key(op.f('alerts_pipeline_id_fkey'), 'alerts', 'pipelines', ['pipeline_id'], ['id'])
    op.create_foreign_key(op.f('alerts_alert_config_id_fkey'), 'alerts', 'alert_configs', ['alert_config_id'], ['id'])
    op.create_foreign_key(op.f('alerts_job_id_fkey'), 'alerts', 'jobs', ['job_id'], ['id'])
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alert_configs_id'), 'alert_configs', ['id'], unique=False)
    # ### end Alembic commands ###
